### ISSUE TITLE
Use portable RNG code

### ISSUE THREAD

**Issue by hollasch** [RayTracing/InOneWeekend#68]
The current codebase relies on the `drand48()` function, which does not exist on Windows.

There are two likely solutions to this:
1. Include a simple, public-domain-as-possible source file that implements a decent RNG, or
2. Use C++ standard `<random>` library functions. (http://www.cplusplus.com/reference/random/).

This work includes the necessary changes to the book material to reflect any new approach.

**Comment by fsan** [comment]
Hello, here is my suggestion

```inline double fRand() {
    return random()/RAND_MAX;
}```

But it is slower than drand48
There could be a nXM precompiled random table of numbers too

**Comment by ronaldfw** [comment]
I believe random() is Linux only. For certain it's not defined in the standard headers on my Windows 10 machine. 

Apart from that, we need one tiny but important change: We need a random number in the interval [0, 1), that is, with 1 being exclusive (according to Chapter 6 in the book). 

With this, the suggestion then would be: 

inline float random_float_1() { 
  return rand() / (RAND_MAX + 1.f);
}

(Personally I would probably add explicit float casts but type promotion ensures that everything works as desired.)

With <random> we can use std::uniform_real_distribution<float>(0.f, 1.f) (which generates a random number in the interval [0, 1), which is what we want). This would look as follows:

float random_float_2() {
  static std::uniform_real_distribution<float> distribution(0.f, 1.f);
  static std::mt19937 generator;
  static std::function<float()> rand_generator = std::bind(distribution, generator);
  return rand_generator();
}

The first version (random_float_1) seems to be a little faster.

random_float_1(), 800x600 resolution, 50 samples, final scene in book:  ~87s
random_float_2(), 800x600 resolution, 50 samples, final scene in book: ~93s

I also tried [this drand48 implementation](https://www.cs.bham.ac.uk/research/projects/poplog/src/master/S.pcwnt/extern/src/rand48.c) 
but that's a lot slower, it took ~122s to render the same scene.

I'll try if the first and also simplest option is portable to Mac and Linux. If yes, I think we should just go with that!?

**Comment by trevordblack** [comment]
We're in the middle of a _fierce_ floats versus doubles debate.

Do double versions of those headers exist?
If they're float only, that may settle the argument.

**Comment by ronaldfw** [comment]
Everything I wrote up there can be done in either float or double: rand() actually returns an integer (and the float/double you get by dividing), and std::uniform_real_distribution can be instantiated with float or double (or long double). 

Interesting that you bring this up, as I was wondering whether it actually makes a difference here (in my implementation of the book I just used float throughout). Have you done any image quality comparisons?

**Comment by ronaldfw** [comment]
Of course, if there is no performance (speed) difference between float and double, then there's no point in making image quality comparisons.

**Comment by hollasch** [comment]
`double`s are a tiny bit faster in many cases, but not enough to tilt the decision in any direction. I think images might be a tiny bit _different_ in some cases (torture-test reflectivity world?), but not _better_, particularly with the inherently noisy sampling we're doing anyway.

I think your random approach sounds good. Let us know what you end up with!

**Comment by ronaldfw** [comment]
Yes, agree that images will probably look different in some cases, but I would have to take a look at actual comparisons to make a call (have never done such a comparison myself).

**Comment by ronaldfw** [comment]
One other thing with using <random> is that this is C++11 only. I don't think we have discussed yet whether we want to go down that path at some point, but that would be another reason to just go with rand() / (RAND_MAX + 1) (and postpone the discussion and decision whether we want to allow C++11 only code).

**Comment by ronaldfw** [comment]
The book already mentions `<random>`, so I'd also be fine with mentioning code for both options in the book, but someone else (Steve, Peter) will have to make the call there.

**Comment by ronaldfw** [comment]
Still need to update the book parts before opening a pull request, but the code changes are here: https://github.com/RayTracing/InOneWeekend/tree/ronaldfw/random

**Comment by hollasch** [comment]
In the discussion around better handling of memory allocation/deallocation, we're circling around using `unique_ptr` and `shared_ptr`, which also requires C++11. I'm generally in favor of adopting C++11 features (or any future features) if they yield code that is generally easier to understand.

**Comment by ronaldfw** [comment]
Agree on C++11 and taking advantage of simplifications we get from using that. In this case, the C++11 code is more complicated and therefore for the code part I ended up choosing what you get with `<cstdlib>`. The book contains snippets for both approaches.

Since all code and book changes are merged, I'll close this issue.
